### ISSUE TITLE
Find asset audience UUIDs

### ISSUE THREAD

**Issue by nicolas17** [hack-different/wwdc23-tasks#3]
There will be new Pallas asset audience UUIDs for new OS version betas (iOS 17 developer/public beta, etc), and for xrOS. Find them and document them.

Update [Siguza's OTA shell script](https://gist.github.com/Siguza/0331c183c8c59e4850cd0b62fd501424) and [DhinakG's audience list](https://gist.github.com/dhinakg/047084eddf232ed61ad4864b789e7088).

**Comment by dhinakg** [comment]
```
77c3bd36-d384-44e8-b550-05122d7da438  Sonoma DB
7ae7f3b9-886a-437f-9b22-e9f017431b0e  watchOS 10 DB
61693fed-ab18-49f3-8983-7c3adf843913  tvOS 17 DB
9dcdaf87-801d-42f6-8ec6-307bd2ab9955  iOS 17 DB
```

**Comment by nicolas17** [comment]
Dhinak's gist is updated now
